-- Minimal help generator. Reads module annotations and emits a vimdoc
-- skeleton. For now it writes a hand-curated stub.

local out = {}

local function put(s) out[#out + 1] = s or '' end

put('*translate.txt*  Translation plugin for Neovim')
put('')
put('==============================================================================')
put('CONTENTS                                                  *translate-contents*')
put('')
put('  1. Usage ........................................... |translate-usage|')
put('  2. Configuration .................................. |translate-config|')
put('  3. Functions ...................................... |translate-functions|')
put('  4. Health ......................................... |translate-health|')
put('')
put('==============================================================================')
put('1. Usage                                                    *translate-usage*')
put('')
put('  >lua')
put('    require("translate").setup({')
put("      target_lang = 'zh-Hans',")
put("      source_lang = 'auto',")
put("      target = 'eol',")
put('    })')
put('  <')
put('')
put('==============================================================================')
put('2. Configuration                                       *translate-config*')
put('')
put('  target_lang                            default: "zh-Hans"')
put('  source_lang                            default: "auto"')
put('  target       (echo|buffer|eol|below|inline|replace)')
put('                                          default: "eol"')
put('  http_timeout (ms)                      default: 30000')
put('')
put('==============================================================================')
put('3. Functions                                          *translate-functions*')
put('')
put('  setup({opts})                                *translate.setup()*')
put('        Initialise the plugin. Must be called once.')
put('')
put('  region()                                    *translate.region()*')
put('        Translate the current selection (or word under cursor).')
put('')
put('  immer.enable([buf])                       *translate.immer.enable()*')
put('  immer.disable([buf])                     *translate.immer.disable()*')
put('  immer.resync([buf])                       *translate.immer.resync()*')
put('        Immersive mode. enable attaches a debounced watcher;')
put('        disable detaches and clears extmarks; resync forces an')
put('        immediate re-translation.')
put('')
put('==============================================================================')
put('4. Health                                              *translate-health*')
put('')
put('  :checkhealth translate')
put('')
put('  Reports whether setup() has been called and which render target')
put('  is active.')
put('')
put('vim:tw=78:ts=8:noet:ft=help:norl:')

local f = io.open('doc/translate.txt', 'w')
f:write(table.concat(out, '\n') .. '\n')
f:close()
